### ISSUE TITLE
Set up live and beta environment

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/jncc-website#21]
Remaining:
- [x] Make vdirs use D: drive
- [x] Create new databases and connect to them
- [x] C6 access to Octopus
- [x] Check IT is backing up deployment-srv
- [x] Check Topcat dev/beta are still deploying OK!
- [x] Firewall rule for Beta (C6 / JNCC access)
- [x] Add vdirs to all environments
- [ ] Document deployment

**Comment by LynnHeeley** [comment]
just editing environment. C6 access to editing server, account set up

**Comment by LynnHeeley** [comment]
in thinking include two ? additional websites for mappers

**Comment by felixMasonJncc** [comment]
[https://app.zenhub.com/files/129929612/119c1bd6-e9d3-4230-85fd-cad77396697f/download](https://app.zenhub.com/files/129929612/119c1bd6-e9d3-4230-85fd-cad77396697f/download)
