### ISSUE TITLE
Auto link from Science Detail page to DataHub

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/jncc-website#31]
Function of 'related content from data hub'; appears in RH menu if editor has populated this function in the template
**Objective** - to list N most relevant resources in the DataHub that are related to the webpage, plus a link to the DH that lists all relevant resources
**Usage** - author creates web page and if there is related content in DH that the author wants to signpost they can:
- visit DH and create a search that lists resources relevant to the web page (multiple search terms allowed)
- obtain a URL or string or token represents the search terms used, to transfer to Umbraco
- paste the URL or string or token into the Umbraco UI
- select the number of relevant links to show (max 6?)
- at runtime the search terms captured above are used to query the search API and render the N links, which each point to assets on the DH
- beneath the N links is a further hyperlink 'see all resources' which loads the DH search results page with the search terms captured above applied.  The top N results on the SRP will match the resources as listed on the Science detail page.

Please see companion Datahub issue jncc/datahub/issues/80

**Comment by PeteMontgomery** [comment]
Best initial idea is for C6 parse the Hub search URL (using standard .net lib) and get the `q` and the `k` parameters from the querystring. 
- You would need to construct an ES query using `q` as the search string to reproduce the Datahub query. 
- Have to make sure that you're doing essentially exactly the same search as the Datahub. 
- If search by keyword is a requirement you will also have to parse the `k` which will harder. 

We need to confirm 100% the search "api" that the Hub uses.

**Comment by carbonsixdigitalpbm** [comment]
It was never my intent that we would be parsing Hub search URLs.  I want to be passing around Elastic Search URLs, which is a clean and well understood API.  I've spoken to Alex and Gemma who both understand this, while I'l away.

**Comment by PeteMontgomery** [comment]
Looks promising https://stackoverflow.com/questions/28939022/get-raw-query-from-nest-client

**Comment by ulric-wilson** [comment]
I'm still keen we have this feature if possible, but if it is going to divert too much resource to sort out it may have to wait until core of DataHub is delivered.  Pete is doing  quick investigation (see above)  to see if we can delivery an ES query to expose to author/editor.

**Comment by PeteMontgomery** [comment]
As demoed / discussed at today's dev meeting. The solution implemented in jncc/datahub#81 is now available and passed to C6 to explore.
