### ISSUE TITLE
Create virtual directory to host manually published files

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/jncc-website#32]
To create capability to host manually published assets (mostly PDFs) on JNCC website that does not compromise code deployment or CMS publishing.
- use of virtual directory in IIS proposed at Dev meeting 12/2/2019
- content in these folders are not managed in Umbraco or Git but are manually copied to webserver by JNCC staff
**Use case** - SAC and SPA Natura 2000 Standard Data Forms ('N2K forms') and Ramsar Information Sheets (RIS) will be direct linked from tables in the website but the links will be generated programmatically and copy-pasted into Umbraco.

**Comment by PeteMontgomery** [comment]
This is part of env setup. Adding @felixMasonJncc also. 😛

**Comment by felixMasonJncc** [comment]
Folder to be called jncc-assets

Create in all environments

**Comment by felixMasonJncc** [comment]
Created on all environments website/jncc-assets pointes to d:\JnccAssets. The same folder is shared between dev and beta as I don't envisage the content changing between environments. It is a simple change to alter if needs be.
