### ISSUE TITLE
Brexit Banner for Alterian JNCC website

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/jncc-website#33]
In case of no-deal Brexit (and possibly in case of all Brexit scenarios) there is a need to incorporate into every page of the current Alterian powered JNCC website (and microsites) a 'banner' / notification with a piece of disclaimer text and a hyperlink to a new page on Alterian JNCC website (to be created).

Text for banner likely to be

"Information on this webpage should be read in the context of recent changes following the United Kingdom’s departure from the European Union. **Further information...**"

where bold text is link to JNCC webpage providing context of Brexit for JNCC advice etc.

Assume best way of doing this is Javascript include that can be added to all templates.

Requester is Calum Watt and contact is Emma Durham / web team

**Comment by ulric-wilson** [comment]
Clare Whitfield has confirmed that April 12th will be earliest time the banner will need to  go live.  But it needs to be ready to go at that date.  Final text to be confirmed later this week.  Text content of banner needs to be easy to update i.e. update in one place to  be reflected in banners on all Alterian templates.

**Comment by mattdebont** [comment]
Will need to add a cookie to the cookies page
