### ISSUE TITLE
Ensure archive.jncc.gov.uk is not discoverable by search engines

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#48]
not sure how best to do this
but no index no follow in all headers is one thought
a robots txt file change also

also wondering if the archive site should be a copy of the current live site, which will allow us to do all these changes prior to live

[https://app.zenhub.com/files/129929612/0af5e9f8-1e33-4f17-bb2a-2a9753bac784/download](https://app.zenhub.com/files/129929612/0af5e9f8-1e33-4f17-bb2a-2a9753bac784/download)

![301-302-404.PNG](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/214b6931-2265-484f-ab72-ae92201a4850)

**Comment by jonparsonsjncc** [comment]
set up http headers in IIS
and put robots page

NOTE - this task can only be done on or just before the site goes live

**Comment by mattdebont** [comment]
Added X-Robots-Tag - noindex, nofollow header to every request coming out from IIS for the old alterian site, the robots.txt file has been returned to normal as google requires access and adding Dissallow / to the file means that the archive site shows up in the main google index anyway.
