### ISSUE TITLE
Update 404 page on http://jncc.defra.gov.uk/error

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#53]
We need to ensure http://jncc.defra.gov.uk/ has a 404 page - with text highlighting that there is a new website with more up to date information

Hi @CathyJinJNCC see wording to add below

Sorry, we've not been able to find the page or file you requested.

This is the archive of the old website - for more up to date information please visit our new website home page - or you can continue to browse from the navigation above or use the search to find the information you need.

Alternatively, you can search and browse for information from previous versions of the JNCC website on the UK Government Web Archive or feel free to contact us.

URLS
https://webarchive.nationalarchives.gov.uk/*/jncc.defra.gov.uk
https://jncc.gov.uk/contact/?ref=archive404

see content below

![301-302-404.PNG](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/58dce622-3a6d-47e0-bcc3-74a7984faff0)

**Comment by CathyJinJNCC** [comment]
Done a very simple static page. I removed the text about the browsing and searching as there is no menu/search bar.
