### ISSUE TITLE
Ensure all domain variants resolve to correct new URL

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#54]
Ensure domains such as
https://www.jncc.gov.uk
http://www.jncc.gov.uk
http://jncc.gov.uk
and any other variant

all resolve to 

https://jncc.gov.uk

also need to set up https for https://www.jncc.gov.uk

doc below for reference

![301-302-404.PNG](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/625e6636-9d75-4c0a-8ded-db5c204d8023)

**Comment by mattdebont** [comment]
All of these redirects are now working
