### ISSUE TITLE
update 500 page http://pre-live.jncc.gov.uk/error-page.html 

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#57]
this page needs its footer updating to be the same as the live site
the google tag manager code needs to be added - same tag manager code that is in the current site
and the text needs to be changed to:

Sorry we were unable to complete your request but our technical staff have been notified of the issue and will work to resolve it. If the problem persists please feel free to contact us.

Note: contact us needs to be a link to /contact/?ref=500

also could you confirm how the technical staff are going to be notified of this error

**Comment by CathyJinJNCC** [comment]
http://dev-website.jncc.gov.uk/<script>

**Comment by jonparsonsjncc** [comment]
Hi @CathyJinJNCC happy for you to deploy to live
