### ISSUE TITLE
issues with archive.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#62]
see attached screen shot
![archive.PNG](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/296b0473-eee4-4b80-89d6-40c92eaccf64)

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont 
see attached doc of all 404s
could you have a look through and see if any are caused by the domain change
[https://app.zenhub.com/files/129929612/0a87e77c-b541-461b-8d90-cb991dad17e9/download](https://app.zenhub.com/files/129929612/0a87e77c-b541-461b-8d90-cb991dad17e9/download)

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont and also these individual ones to archive

http://archive.jncc.gov.uk/page-6329	http://archive.jncc.gov.uk/default.aspx?page=3128
http://archive.jncc.gov.uk/default.aspx?page=4174&gcr=3125	http://archive.jncc.gov.uk/earthheritage/gcrdb/gcr_maps/3125_thumb.gif
http://archive.jncc.gov.uk/default.aspx?page=4174&gcr=3276	http://archive.jncc.gov.uk/earthheritage/gcrdb/gcr_maps/3276_thumb.gif
http://archive.jncc.gov.uk/page-7507	http://cms/http://jncc.defra.gov.uk/page-6849

**Comment by mattdebont** [comment]
Made recommendations on 404's in spreadsheet, above changes are out of my hands for the most part and are part of the old site, either missing or mistyped content
