### ISSUE TITLE
Formatting on the published dates for the website asset results

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#66]
Formatting on the published dates for the website asset results? e..g https://jncc.gov.uk/search?q=natura the dates could look more human readable

also be aware that there is a ticket

**Comment by felixMasonJncc** [comment]
Done

NB this testing encompasses the broader testing of the asset indexer - jncc-website / 45

The asset indexer downloads a set of specified CSV's from the website. The CSV's contain a list of pdf files and some information about them. The pdfs reside in the same location as the corrisponding csv

1) Download the CSV's from the live site:
http://jncc.gov.uk/jncc-assets/RIS/RAMSAR_1.csv
http://jncc.gov.uk/jncc-assets/SAC-N2K/SAC_1.csv
http://jncc.gov.uk/jncc-assets/SPA-N2K/SPA_1.csv

2) Open the CSV's and select a few pdfs
3) Get the pdf's by substituing there file name for the csv file name in the url of the corrisponding csv. Ie to get a ramsar pdf called UK11034.pdf you would use the following URL
http://jncc.gov.uk/jncc-assets/RIS/UK11034.pdf

With the selection of PDFs and data you should be able to search for the following:

- The title of the PDF from the spreadsheet
- Some contents from the pdf

You should be able to view the pdf from the search result and it should be the same as the one you downloaded manually

The publication date should be the same as the date in the csv

Known Issues:
- Some of the RAMSAR pdf's are missing
- The pdfs do not have the title metadata set. This means that they show up as <some site> - untitled in the search results. This is an issue with the pdf creation.
