### ISSUE TITLE
Set up demo of openspace map

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#68]
To test if the new API key is valid

8DCC3F3A1C6711EDE0530B6CA40A40DD 

using the code attached in the file

[https://app.zenhub.com/files/132160057/5177b94a-e3e0-4cb6-9ca3-021f70f68972/download](https://app.zenhub.com/files/132160057/5177b94a-e3e0-4cb6-9ca3-021f70f68972/download)

to ultimately try and understand what the problem is with these pages

http://archive.jncc.gov.uk/smp/

**Comment by mattdebont** [comment]
Tried to recreate with new key account set up with `http://archive.jncc.gov.uk` and `http://archive.jncc.gov.uk/` neither work and both throw a HTTP referrer header not valid
