### ISSUE TITLE
Update sac pdf's and map pages as a result of article 17

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#70]

**Comment by jonparsonsjncc** [comment]
Hi @felixMasonJncc 
the files for the article 17 task are stored on the network - I will skype you a link
these 637 files need adding to a new folder called
https://jncc.gov.uk/jncc-assets/Art17/
the search needs to be made aware of these files - but the issue of duplicate titles in the ingester needs to be resolved first
Also I need to get confirmation from Emma before we can do this as this will make the files available in the search and the main pages arent ready yet
So please hold off until i can confirm

**Comment by felixMasonJncc** [comment]
Loaded into beta website using new lambda.

**Comment by felixMasonJncc** [comment]
New code won't deploy for a couple of reasons.

Maven dependency issues arising probably from a tikka library update (due to a security issues)
Jenkins job reports successful even when it fails ?

**Comment by CathyJinJNCC** [comment]
Deployed to beta and looks good (no duplicates). Might want to consider what topcat results will look like using this new logic (might have duplicate results now, though there'll be no duplicates within a result title). Consider: https://jncc.gov.uk/search?q=biodiversity+indicators

Also there are SAC results with "untitled" in the name, which looks like a content issue and something you may want to look into @jonparsonsjncc
